server:
  port: 8020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cloud-web-demo
feign:
  hystrix:
    enabled: true
management:
  server:
    port: 7001
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor
    health:
      show-details: always
debug: true
security:
  oauth2:
    client:
      client-id: demo_resource
      client-secret: user123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key