server:
  port: 8090
  servlet:
    context-path: /portal
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
zuul:
  ignoreSecurityHeaders: false
  sensitiveHeaders: #不忽略任何头部信息，所有header都转发到下游的资源服务器。上下游session共享
  routes:
    cloud-web-demo: /shf/**
  retryable: false
  add-proxy-headers: true
security:
  oauth2:
    client:
      client-id: UserManagement
      client-secret: user123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
jwt:
  tokenHead: Bearer
  header: Authorization
  expiration: 1800
  secret: mySecret
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


