spring:
  datasource:
    url: jdbc:mysql://192.168.6.133:3306/demo_cjs_oauth2
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 192.168.6.133
    port: 6379
server:
  port: 8080