spring:
  datasource:
    url: jdbc:mysql://shf.com:3306/demo_cjs_oauth2
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
#  session:
#    store-type: redis
  redis:
    host: shf.com
    port: 6379
    database: 2
server:
  port: 8080